version: '3.8'
services:
  login-service:
    build:
      context: ./login-service
      dockerfile: Dockerfile
    container_name: login-service
    ports:
      - 8000:8000
    volumes:
      - ./login-service/:/var/www
    networks:
      - login
      - microservices
    depends_on:
      - login-db
      - rabbitmq

  login-db:
    image: mysql:8.0
    container_name: login-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_db
      MYSQL_USER: login
      MYSQL_PASSWORD: secret
    networks:
      - login
    volumes:
      - login_db_data:/var/lib/mysql

  log-service:
    build:
      context: ./log-service
      dockerfile: Dockerfile
    container_name: log-service
    volumes:
      - ./log-service/:/var/www
    networks:
      - log
      - microservices
    depends_on:
      - log-db
      - rabbitmq

  log-db:
    image: mysql:8.0
    container_name: log-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: log_db
      MYSQL_USER: log
      MYSQL_PASSWORD: secret
    volumes:
      - log_db_data:/var/lib/mysql
    networks:
      - log

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
  login:
    driver: bridge
  log:
    driver: bridge

volumes:
  login_db_data:
  log_db_data:
